// lib/data/game_constants.dart

import 'package:dynamic_list_app/widgets/game_list.dart';
import 'package:flutter/material.dart';

// Button Gradient Colors
const List<Color> greenButtonGradient = [Color(0xFF4CAF50), Color(0xFF388E3C)];
const List<Color> orangeButtonGradient = [Color(0xFFEABE66), Color(0xFFC3872E)];

// Card Gradient Colors
const List<Color> practiceCardGradient = [Color(0xFFFFF0D4), Color(0xFFFFFFFF)];
const List<Color> pointValueCardGradient = [
  Color(0xFFFFFFFF),
  Color(0xFFFFFFFF)
];
const List<Color> overGradientColor = [
  Color(0xFFE7C691),
  Color(0xFFE7C691)
]; // OverGradientColor

// Game Options Data
const List<Map<String, dynamic>> gameOptions = [
  {
    'type': GameOptionType.practice,
    'title': 'Practice',
    'entryFee': 0,
    'playerCount': '2',
    'buttonText': 'PLAY',
    'isRecommended': false,
    'cardGradientColors': practiceCardGradient,
    'overlayGradientColors': overGradientColor,
    'borderRadius': 15.0,
    'buttonGradientColors': greenButtonGradient,
    'tagLabel': '',
    'borderColor': Color(0xFFE7C691),
  },
  {
    'type': GameOptionType.pointValue,
    'title': '0.0125',
    'entryFee': 5,
    'playerCount': '2',
    'buttonText': 'ADD CASH',
    'isRecommended': true,
    'cardGradientColors': pointValueCardGradient,
    'overlayGradientColors': overGradientColor,
    'borderRadius': 15.0,
    'buttonGradientColors': orangeButtonGradient,
    'tagLabel': 'Recommended',
    'borderColor': Colors.white,
  },
  {
    'type': GameOptionType.pointValue,
    'title': '0.0125',
    'entryFee': 1,
    'playerCount': '2',
    'buttonText': 'ADD CASH',
    'isRecommended': true,
    'cardGradientColors': pointValueCardGradient,
    'overlayGradientColors': overGradientColor,
    'borderRadius': 15.0,
    'buttonGradientColors': orangeButtonGradient,
    'tagLabel': 'Recommended',
  },
  {
    'type': GameOptionType.pointValue,
    'title': '0.0125',
    'entryFee': 10,
    'playerCount': '2',
    'buttonText': 'ADD CASH',
    'isRecommended': false,
    'cardGradientColors': pointValueCardGradient,
    'overlayGradientColors': practiceCardGradient,
    'borderRadius': 15.0,
    'buttonGradientColors': orangeButtonGradient,
    'tagLabel': 'Recommended',
  },
  {
    'type': GameOptionType.pointValue,
    'title': '0.0125',
    'entryFee': 1,
    'playerCount': '2',
    'buttonText': 'ADD CASH',
    'isRecommended': false,
    'cardGradientColors': pointValueCardGradient,
    'overlayGradientColors': practiceCardGradient,
    'borderRadius': 15.0,
    'buttonGradientColors': orangeButtonGradient,
    'tagLabel': 'Recommended',
  },
  {
    'type': GameOptionType.pointValue,
    'title': '0.0125',
    'entryFee': 80,
    'playerCount': '2',
    'buttonText': 'ADD CASH',
    'isRecommended': false,
    'cardGradientColors': pointValueCardGradient,
    'overlayGradientColors': practiceCardGradient,
    'borderRadius': 15.0,
    'buttonGradientColors': orangeButtonGradient,
    'tagLabel': 'Recommended',
  },
  {
    'type': GameOptionType.pointValue,
    'title': '0.0125',
    'entryFee': 1,
    'playerCount': '2',
    'buttonText': 'ADD CASH',
    'isRecommended': false,
    'cardGradientColors': pointValueCardGradient,
    'overlayGradientColors': practiceCardGradient,
    'borderRadius': 15.0,
    'buttonGradientColors': orangeButtonGradient,
    'tagLabel': 'Recommended',
  },
  {
    'type': GameOptionType.pointValue,
    'title': '0.0125',
    'entryFee': 1,
    'playerCount': '6',
    'buttonText': 'ADD CASH',
    'isRecommended': false,
    'cardGradientColors': pointValueCardGradient,
    'overlayGradientColors': pointValueCardGradient,
    'borderRadius': 15.0,
    'buttonGradientColors': orangeButtonGradient,
    'tagLabel': 'Recommended',
  },
  {
    'type': GameOptionType.pointValue,
    'title': '0.0125',
    'entryFee': 8,
    'playerCount': '6',
    'buttonText': 'ADD CASH',
    'isRecommended': false,
    'cardGradientColors': pointValueCardGradient,
    'overlayGradientColors': pointValueCardGradient,
    'borderRadius': 15.0,
    'buttonGradientColors': orangeButtonGradient,
    'tagLabel': 'Recommended',
  },
  {
    'type': GameOptionType.pointValue,
    'title': '0.0125',
    'entryFee': 1,
    'playerCount': '2',
    'buttonText': 'ADD CASH',
    'isRecommended': false,
    'cardGradientColors': pointValueCardGradient,
    'overlayGradientColors': pointValueCardGradient,
    'borderRadius': 15.0,
    'buttonGradientColors': orangeButtonGradient,
    'tagLabel': 'Recommended',
  },
  {
    'type': GameOptionType.pointValue,
    'title': '0.0125',
    'entryFee': 1,
    'playerCount': '2',
    'buttonText': 'ADD CASH',
    'isRecommended': false,
    'cardGradientColors': pointValueCardGradient,
    'overlayGradientColors': pointValueCardGradient,
    'borderRadius': 15.0,
    'buttonGradientColors': orangeButtonGradient,
    'tagLabel': 'Recommended',
  },
  {
    'type': GameOptionType.pointValue,
    'title': '0.0125',
    'entryFee': 1,
    'playerCount': '2',
    'buttonText': 'ADD CASH',
    'isRecommended': false,
    'cardGradientColors': pointValueCardGradient,
    'overlayGradientColors': pointValueCardGradient,
    'borderRadius': 15.0,
    'buttonGradientColors': orangeButtonGradient,
    'tagLabel': 'Recommended',
  },
  // {
  //   'type': GameOptionType.pointValue,
  //   'title': '0.0125',
  //   'entryFee': '1',
  //   'playerCount': '3',
  //   'buttonText': 'ADD CASH',
  //   'isRecommended': false,
  //   'cardGradientColors': pointValueCardGradient,
  //   'overlayGradientColors': pointValueCardGradient,
  //   'borderRadius': 15.0,
  //   'buttonGradientColors': orangeButtonGradient,
  //   'tagLabel': 'Recommended',
  // },
];

// ₹